import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:inventory_system/features/role/models/roles.dart';

class RoleService {
  final FirebaseFirestore _db = FirebaseFirestore.instance;

  Future<Role> createRole(
      String name, Set<Permission> permissions, String companyId) async {
    final role = Role(
      id: '', // ID will be generated by Firestore
      name: name,
      permissions: permissions,
      companyId: companyId,
    );

    final docRef = await _db.collection('roles').add(role.toMap());
    return Role(
      id: docRef.id,
      name: role.name,
      permissions: role.permissions,
      companyId: role.companyId,
    ); // Update the role with the generated ID
  }
}
