// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASA7e1_gF-bmkKb5KFoR9-oZrycJDj0Ks',
    appId: '1:535365513797:web:226dd9a9151094744d692c',
    messagingSenderId: '535365513797',
    projectId: 'warehouse-and-logistics-order',
    authDomain: 'warehouse-and-logistics-order.firebaseapp.com',
    storageBucket: 'warehouse-and-logistics-order.appspot.com',
    measurementId: 'G-V3N1GKE7WE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSsAS0EbfLf4exBHnWBkNb6vR3zCnRGWw',
    appId: '1:535365513797:android:80388ad677d3989d4d692c',
    messagingSenderId: '535365513797',
    projectId: 'warehouse-and-logistics-order',
    storageBucket: 'warehouse-and-logistics-order.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxoyZeWR0T5IG0Gf_TEpv7D5G6XTRl5Wk',
    appId: '1:535365513797:ios:4b77cfe6988caf394d692c',
    messagingSenderId: '535365513797',
    projectId: 'warehouse-and-logistics-order',
    storageBucket: 'warehouse-and-logistics-order.appspot.com',
    iosBundleId: 'com.example.inventorySystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxoyZeWR0T5IG0Gf_TEpv7D5G6XTRl5Wk',
    appId: '1:535365513797:ios:4b77cfe6988caf394d692c',
    messagingSenderId: '535365513797',
    projectId: 'warehouse-and-logistics-order',
    storageBucket: 'warehouse-and-logistics-order.appspot.com',
    iosBundleId: 'com.example.inventorySystem',
  );
}
